import FormItemGeneratorToDict,{Components,components as FormItemGeneratorToDictComponents}from"./FormItemGeneratorToDict";export default{Components:Components,FormItemGeneratorToDict:FormItemGeneratorToDict,FormItemGeneratorToDictComponents:FormItemGeneratorToDictComponents};
//# sourceMappingURL=index.js.map
