import AnimationManager from './AnimationManager';
import GeoLayer from './GeoLayer';
import HeatMap from './HeatMap';
import OLMap from './OLMap';
import * as TitleLayer from './TitleLayer';
import Util from './Util';
export type { OLMapProps, MapType, MapTypeValue, MapConfig, GeoJSONStyle, HeatMapConfig, AnimationConfig, DrawParams, PointDrawParams, ImagePointParams, InteractionConfig, MapEventCallbacks, MapInstance, DrawCircleParams, DrawPolygonParams, DrawLineParams, DrawCirclePointParams, DrawRegularShapePointParams, DrawImagePointParams, SetMapCenterAnimateParams, CreateInteractionParams, PolygonInteractionParams, CircleInteractionParams, BoxInteractionParams, LinStringInteractionParams, CreateModifyInteractionParams, AddArrowsSourceParams, HeatMapProps, OLMapState, } from './types';
export type { HeatMapLayerConfig } from './HeatMap';
export { default as Constant } from './Constant';
export { MAP_TYPE_ADMINISTRATIVE, MAP_TYPE_SATELLITE } from './Constant';
export { AnimationManager, GeoLayer, TitleLayer, OLMap, HeatMap, Util };
declare const defaultExport: {
    AnimationManager: typeof AnimationManager;
    GeoLayer: typeof GeoLayer;
    TitleLayer: typeof TitleLayer;
    OLMap: import("react").ForwardRefExoticComponent<import("./types").OLMapProps & import("react").RefAttributes<import("./OLMap").OlMap>>;
    HeatMap: typeof HeatMap;
    Util: {
        SHOW_BASE_STATION_MIN_ZOOM: number;
        getMinZoom: (target: HTMLElement) => number;
        transformLonLat: (point: number[]) => number[];
        createMap: (Config: import("./Util").CreateMapConfig) => import("ol").Map;
        setOverlayState: (overlay: import("ol").Overlay, point: number[]) => void;
        addClickListener: (mapInstance: import("ol").Map, listeningLayer: import("ol/layer").Vector<any>, hitCallback: ((feature: import("ol").Feature | any) => void) | undefined, unHitCallback: ((feature: import("ol").Feature | any) => void) | undefined, setCursor: (cursor: string) => void) => void;
        addHoverListener: (mapInstance: import("ol").Map, listeningLayer: import("ol/layer").Vector<any>, hitCallback: (feature: import("ol").Feature | any) => void, unHitCallback: (feature: import("ol").Feature | any) => void) => void;
        addGeoLayer: (mapInstance: import("ol").Map, geoJsonData: any, getStyleConfig?: any, zIndex?: number) => GeoLayer;
        addWindLayer: (mapInstance: import("ol").Map, data: any, config: any, zIndex?: number) => import("./WindLayer").default;
        addVectorLayer(map: import("ol").Map, zIndex: number): {
            vectorLayer: import("ol/layer").Vector<any>;
            vectorSource: import("ol/source").Vector;
        };
        createHeatMapLayer(layoutConfig: any): {
            layer: import("ol/layer").Heatmap;
            vectorSource: import("ol/source").Vector;
        };
        drawCircle({ center, radius, color, strokeColor, strokeWidth, zIndex, id, properties, }: import("./types").DrawCircleParams): import("ol").Feature;
        drawPolygon({ points, color, strokeColor, strokeWidth, zIndex, id, properties, }: import("./types").DrawPolygonParams): import("ol").Feature;
        drawLine({ points, width, color, lineCap, lineJoin, lineDash, }: import("./types").DrawLineParams): import("ol").Feature;
        drawCirclePoint({ id, pos, fillOpt, strokeOpt, radius, textOpt, zIndex, text, properties, }: import("./types").DrawCirclePointParams): import("ol").Feature;
        drawRegularShapePoint({ id, pos, points, fillOpt, strokeOpt, text, textOpt, zIndex, properties, ...rest }: import("./types").DrawRegularShapePointParams): import("ol").Feature;
        drawImagePoint({ id, pos, zIndex, src, color, opacity, scale, anchor, rotation, offset, offsetOrigin, size, text, textOpt, properties, }: import("./types").DrawImagePointParams): import("ol").Feature;
        createRegularPolygonCurve(origin: number[], radius: number, sides: number, r: number, angel: number): import("ol/geom").Polygon;
        setMapCenterAnimate({ map, point, duration, ...rest }: import("./types").SetMapCenterAnimateParams): void;
        createInteraction({ map, config }: import("./types").CreateInteractionParams): import("ol/interaction/Draw").default;
        polygonInteraction({ map, freehand, vectorSource, onDrawEnd, ...rest }: import("./types").PolygonInteractionParams): import("ol/interaction/Draw").default;
        circleInteraction({ map, vectorSource, onDrawEnd, ...rest }: import("./types").CircleInteractionParams): import("ol/interaction/Draw").default;
        boxInteraction({ map, vectorSource, onDrawEnd, ...rest }: import("./types").BoxInteractionParams): import("ol/interaction/Draw").default;
        linStringInteraction({ map, freehand, vectorSource, onDrawEnd, ...rest }: import("./types").LinStringInteractionParams): import("ol/interaction/Draw").default;
        createModifyInteraction({ map, vectorSource, onModifyEnd, }: import("./types").CreateModifyInteractionParams): import("ol/interaction/Modify").default;
        removeFeature(vectorSource: import("ol/source").Vector, feature: import("ol").Feature): void;
        removeAllFeature(vectorSource: import("ol/source").Vector): void;
        removeFeaturesByType(vectorSource: import("ol/source").Vector, type: string): void;
        removeAllOverlay(map: import("ol").Map): void;
        removeInteraction(map: import("ol").Map, interaction: any): void;
        removeInteractionAll(map: import("ol").Map): void;
        mapFit(extent: number[] | undefined, option: any | undefined, map: import("ol").Map): void;
        addArrowsSource({ points, color, icon, anchor, offset }: import("./types").AddArrowsSourceParams): import("ol").Feature[];
        addArrowsOverlay(map: import("ol").Map, parentDom: HTMLElement, color: string, points: number[][]): void;
        addOverlay: (map: import("ol").Map, config: any, div: HTMLDivElement | null) => import("ol").Overlay;
        rgb(): string;
        color16(): string;
        getRad(d: number): number;
        wrapLon(value: number): number;
        getMapExtent(map: import("ol").Map): Array<{
            lon: number;
            lat: number;
        }> | false;
        getFeaturesInExtent(map: import("ol").Map, feature: import("ol").Feature): any[];
        getLayersCount(map: import("ol").Map): number;
        getLineColor(index: number): string;
        downLoadMap(map: import("ol").Map): void;
        getRadius(center: number[], radius: number): number;
        getExtentByCoordinates(coordinates: number[][]): number[];
        getExtentByVectorSource(vectorSource: import("ol/source").Vector, type?: string): number[];
        getVectorSourceCoordinates(vectorSource: import("ol/source").Vector, type?: string): number[][];
        getCenterByCoordinates(vectorSource: import("ol/source").Vector, type?: string): {
            centerLon: number;
            centerLat: number;
        };
        getCenterByPoints(points: number[][]): {
            centerLon: number;
            centerLat: number;
        };
        getPointsExtent(points: number[][]): {
            leftTop: number[];
            rightBottom: number[];
        };
        getFlattenDistance(lat1: number, lng1: number, lat2: number, lng2: number): number;
    };
};
export default defaultExport;
